#!/bin/bash
###############################################################################
# DigitalOcean Droplet Setup Script
# 
# This script sets up the weather trading bot on a fresh DigitalOcean droplet
# Run this script on the droplet after SSH'ing in as root
###############################################################################

set -e  # Exit on error

echo "=============================================================================="
echo "DigitalOcean Droplet Setup - Weather Trading Bot"
echo "=============================================================================="
echo ""

# Configuration
PROJECT_DIR="/opt/weather-hunters"
REPO_URL="${1:-https://github.com/YOUR_USERNAME/weather-hunters.git}"  # Pass as arg or set default

echo "Configuration:"
echo "  Project directory: $PROJECT_DIR"
echo "  Repository URL: $REPO_URL"
echo ""

# Step 1: Update system
echo "[1/8] Updating system packages..."
apt update -qq
apt upgrade -y -qq
echo "✓ System updated"
echo ""

# Step 2: Install dependencies
echo "[2/8] Installing system dependencies..."
apt install -y -qq \
    python3.10 \
    python3-pip \
    python3.10-venv \
    git \
    cron \
    curl \
    nano \
    logrotate \
    htop
echo "✓ Dependencies installed"
echo ""

# Step 3: Clone repository
echo "[3/8] Cloning repository..."
mkdir -p $(dirname $PROJECT_DIR)
if [ -d "$PROJECT_DIR" ]; then
    echo "  Directory exists, updating..."
    cd $PROJECT_DIR
    git pull || echo "  Warning: Could not pull (may not be a git repo yet)"
else
    git clone "$REPO_URL" "$PROJECT_DIR" || {
        echo "  ERROR: Could not clone repository"
        echo "  Please ensure:"
        echo "    1. Repository is accessible from this server"
        echo "    2. SSH keys are set up (or use HTTPS with credentials)"
        echo "    3. Repository URL is correct: $REPO_URL"
        exit 1
    }
    cd $PROJECT_DIR
fi
echo "✓ Repository cloned/updated"
echo ""

# Step 4: Create virtual environment
echo "[4/8] Creating Python virtual environment..."
if [ -d "$PROJECT_DIR/venv" ]; then
    echo "  Virtual environment already exists, skipping..."
else
    python3 -m venv "$PROJECT_DIR/venv"
    echo "✓ Virtual environment created"
fi
echo ""

# Step 5: Install Python dependencies
echo "[5/8] Installing Python dependencies..."
source "$PROJECT_DIR/venv/bin/activate"
pip install --upgrade pip -q
pip install -r "$PROJECT_DIR/requirements.txt" -q
echo "✓ Python dependencies installed"
echo ""

# Step 6: Setup environment file
echo "[6/8] Setting up environment configuration..."
if [ ! -f "$PROJECT_DIR/.env" ]; then
    if [ -f "$PROJECT_DIR/.env.template" ]; then
        cp "$PROJECT_DIR/.env.template" "$PROJECT_DIR/.env"
        echo "✓ Created .env from template"
        echo ""
        echo "⚠️  IMPORTANT: Edit .env file with your credentials:"
        echo "   nano $PROJECT_DIR/.env"
        echo ""
        echo "   Required variables:"
        echo "   - KALSHI_API_KEY_ID"
        echo "   - KALSHI_PRIVATE_KEY_FILE (or KALSHI_PRIVATE_KEY)"
        echo ""
        read -p "Press Enter after you've configured .env file..."
    else
        echo "  Warning: .env.template not found, creating basic .env"
        touch "$PROJECT_DIR/.env"
    fi
else
    echo "✓ .env file already exists"
fi
echo ""

# Step 7: Create directories
echo "[7/8] Creating required directories..."
mkdir -p "$PROJECT_DIR/logs"
mkdir -p "$PROJECT_DIR/metrics"
mkdir -p "$PROJECT_DIR/data/weather"
echo "✓ Directories created"
echo ""

# Step 8: Setup cron jobs
echo "[8/8] Setting up cron jobs..."
CRON_FILE="/tmp/weather_bot_cron"
cat > "$CRON_FILE" <<EOF
# Weather Trading Bot - Forward Test Cron Jobs
# Generated by setup script on $(date)

# Morning predictions at 9 AM EST (14:00 UTC)
0 14 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/paper_trade_morning.py >> $PROJECT_DIR/logs/cron_morning.log 2>&1

# Evening settlement at 8 PM EST (01:00 UTC next day)
0 1 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/settle_live_data.py >> $PROJECT_DIR/logs/cron_settle.log 2>&1

# Daily health check at noon EST (17:00 UTC)
0 17 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/health_check.py >> $PROJECT_DIR/logs/cron_health.log 2>&1

# Weekly analysis (every Monday at 2 AM EST = 07:00 UTC)
0 7 * * 1 cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/analyze_paper_trades.py >> $PROJECT_DIR/logs/cron_analysis.log 2>&1
EOF

# Install cron jobs
crontab -l 2>/dev/null > /tmp/current_cron || true
if ! grep -q "weather_bot_cron" /tmp/current_cron 2>/dev/null; then
    cat "$CRON_FILE" | crontab -
    echo "✓ Cron jobs installed"
else
    echo "  Cron jobs already installed, skipping..."
fi
rm -f "$CRON_FILE"
echo ""

# Step 9: Setup log rotation
echo "[9/9] Setting up log rotation..."
cat > /etc/logrotate.d/weather-hunters <<EOF
$PROJECT_DIR/logs/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}
EOF
echo "✓ Log rotation configured"
echo ""

# Summary
echo "=============================================================================="
echo "Setup Complete!"
echo "=============================================================================="
echo ""
echo "Project location: $PROJECT_DIR"
echo "Virtual environment: $PROJECT_DIR/venv"
echo ""
echo "Cron jobs installed:"
crontab -l | grep -v "^#"
echo ""
echo "Next steps:"
echo "  1. Edit .env file with your credentials:"
echo "     nano $PROJECT_DIR/.env"
echo ""
echo "  2. Test morning script manually:"
echo "     cd $PROJECT_DIR"
echo "     source venv/bin/activate"
echo "     python scripts/paper_trade_morning.py"
echo ""
echo "  3. Test settlement script manually:"
echo "     python scripts/settle_live_data.py"
echo ""
echo "  4. Monitor logs:"
echo "     tail -f $PROJECT_DIR/logs/cron_morning.log"
echo "     tail -f $PROJECT_DIR/logs/cron_settle.log"
echo ""
echo "  5. Check cron job status:"
echo "     crontab -l"
echo ""
echo "=============================================================================="
