#!/bin/bash
###############################################################################
# Quick Setup Script - Copy-Paste This Entire Script Into Your Droplet
#
# This script does EVERYTHING automatically:
# - Updates system
# - Installs dependencies
# - Clones repository (or prompts for upload)
# - Sets up Python environment
# - Configures cron jobs
# - Prompts for .env configuration
#
# Just copy-paste this entire script into your SSH session!
###############################################################################

set -e  # Exit on error

echo "=============================================================================="
echo "Weather Trading Bot - Quick Setup"
echo "=============================================================================="
echo ""

# Configuration
PROJECT_DIR="/opt/weather-hunters"
REPO_URL="${1:-}"  # Can pass as argument

# Step 1: Update system
echo "[1/9] Updating system..."
apt update -qq
apt upgrade -y -qq
echo "✓ System updated"
echo ""

# Step 2: Install dependencies
echo "[2/9] Installing system dependencies..."
apt install -y -qq \
    python3.10 \
    python3-pip \
    python3.10-venv \
    git \
    cron \
    curl \
    nano \
    htop
echo "✓ Dependencies installed"
echo ""

# Step 3: Clone or setup repository
echo "[3/9] Setting up repository..."
mkdir -p $(dirname $PROJECT_DIR)

if [ -z "$REPO_URL" ]; then
    echo ""
    echo "Repository URL not provided."
    echo "Options:"
    echo "  1. If repo is on GitHub, provide URL:"
    echo "     Example: ./quick_setup.sh https://github.com/YOUR_USERNAME/weather-hunters.git"
    echo ""
    echo "  2. Or upload files manually via SCP from your local machine:"
    echo "     rsync -avz --exclude 'venv' --exclude '__pycache__' \\"
    echo "       -e 'ssh -i ~/.ssh/weather_bot_key_new' \\"
    echo "       ./ root@165.22.172.211:/opt/weather-hunters/"
    echo ""
    read -p "Do you want to continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
    
    if [ ! -d "$PROJECT_DIR" ]; then
        echo "⚠️  Project directory not found. Please upload files first."
        exit 1
    fi
    cd $PROJECT_DIR
else
    if [ -d "$PROJECT_DIR" ]; then
        echo "  Directory exists, updating..."
        cd $PROJECT_DIR
        git pull || echo "  Warning: Could not pull"
    else
        echo "  Cloning repository: $REPO_URL"
        git clone "$REPO_URL" "$PROJECT_DIR" || {
            echo "  ERROR: Could not clone repository"
            echo "  Please check the URL and try again"
            exit 1
        }
        cd $PROJECT_DIR
    fi
fi
echo "✓ Repository ready"
echo ""

# Step 4: Create virtual environment
echo "[4/9] Creating Python virtual environment..."
if [ -d "$PROJECT_DIR/venv" ]; then
    echo "  Virtual environment already exists, skipping..."
else
    python3 -m venv "$PROJECT_DIR/venv"
    echo "✓ Virtual environment created"
fi
echo ""

# Step 5: Install Python dependencies
echo "[5/9] Installing Python dependencies..."
source "$PROJECT_DIR/venv/bin/activate"
pip install --upgrade pip -q
pip install -r "$PROJECT_DIR/requirements.txt" -q
echo "✓ Python dependencies installed"
echo ""

# Step 6: Setup environment file
echo "[6/9] Setting up environment configuration..."
if [ ! -f "$PROJECT_DIR/.env" ]; then
    if [ -f "$PROJECT_DIR/.env.template" ]; then
        cp "$PROJECT_DIR/.env.template" "$PROJECT_DIR/.env"
        echo "✓ Created .env from template"
    else
        touch "$PROJECT_DIR/.env"
        echo "✓ Created empty .env file"
    fi
else
    echo "✓ .env file already exists"
fi
echo ""

# Step 7: Create directories
echo "[7/9] Creating required directories..."
mkdir -p "$PROJECT_DIR/logs"
mkdir -p "$PROJECT_DIR/metrics"
mkdir -p "$PROJECT_DIR/data/weather"
echo "✓ Directories created"
echo ""

# Step 8: Setup cron jobs
echo "[8/9] Setting up cron jobs..."
CRON_FILE="/tmp/weather_bot_cron"
cat > "$CRON_FILE" <<EOF
# Weather Trading Bot - Forward Test Cron Jobs
# Generated by quick_setup.sh on $(date)

# Morning predictions at 9 AM EST (14:00 UTC)
0 14 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/paper_trade_morning.py >> $PROJECT_DIR/logs/cron_morning.log 2>&1

# Evening settlement at 8 PM EST (01:00 UTC next day)
0 1 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/settle_live_data.py >> $PROJECT_DIR/logs/cron_settle.log 2>&1

# Daily health check at noon EST (17:00 UTC)
0 17 * * * cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/health_check.py >> $PROJECT_DIR/logs/cron_health.log 2>&1

# Weekly analysis (every Monday at 2 AM EST = 07:00 UTC)
0 7 * * 1 cd $PROJECT_DIR && $PROJECT_DIR/venv/bin/python scripts/analyze_paper_trades.py >> $PROJECT_DIR/logs/cron_analysis.log 2>&1
EOF

# Install cron jobs
crontab -l 2>/dev/null > /tmp/current_cron || true
if ! grep -q "weather_bot_cron" /tmp/current_cron 2>/dev/null; then
    cat "$CRON_FILE" | crontab -
    echo "✓ Cron jobs installed"
else
    echo "  Cron jobs already installed, skipping..."
fi
rm -f "$CRON_FILE"
echo ""

# Step 9: Setup log rotation
echo "[9/9] Setting up log rotation..."
cat > /etc/logrotate.d/weather-hunters <<EOF
$PROJECT_DIR/logs/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}
EOF
echo "✓ Log rotation configured"
echo ""

# Summary
echo "=============================================================================="
echo "Setup Complete!"
echo "=============================================================================="
echo ""
echo "Project location: $PROJECT_DIR"
echo "Virtual environment: $PROJECT_DIR/venv"
echo ""
echo "Cron jobs installed:"
crontab -l | grep -v "^#" | head -4
echo ""
echo "⚠️  IMPORTANT: Configure your .env file with Kalshi credentials:"
echo ""
echo "   nano $PROJECT_DIR/.env"
echo ""
echo "   Add these lines:"
echo "   KALSHI_API_KEY_ID=your_key_id_here"
echo "   KALSHI_PRIVATE_KEY_FILE=$PROJECT_DIR/kalshi_private_key.pem"
echo ""
echo "   OR if using inline key:"
echo "   KALSHI_PRIVATE_KEY=your_full_private_key_here"
echo ""
echo "Next steps:"
echo "  1. Edit .env file: nano $PROJECT_DIR/.env"
echo "  2. Upload private key (if using file): scp from local machine"
echo "  3. Test manually: cd $PROJECT_DIR && source venv/bin/activate && python scripts/paper_trade_morning.py"
echo "  4. Monitor logs: tail -f $PROJECT_DIR/logs/cron_morning.log"
echo ""
echo "=============================================================================="
